### ISSUE TITLE
Error en la hora de fin de subasta

### ISSUE THREAD

**Issue by doviarab** [drizak/DBot#2]
Existen 4 horas de diferencia en el mensaje de "Auction End" de las waifus. (Indica que termina a las 13:00, cuando se refiere a las 09:00)
![imagen](https://user-images.githubusercontent.com/19767561/82053199-f6e3d100-968a-11ea-9e96-c200f80a7d4f.png)

**Comment by aab626** [comment]
jejej arreglado, tenia la caga con una mezcla de tiempos utc y con la hora de chile, aproveche de normalizar todo esop
